language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --no-suggest --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - scrub.mx@gmail.com
