name: PHPUnit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ci:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['7.2.5', '7.3', '7.4', '8.0', '8.1', 8.2', '8.3']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install Composer Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 2
          max_attempts: 4
          command: composer update --no-interaction --no-progress --ansi

      - name: Run Tests
        run: vendor/bin/phpunit
